### ISSUE TITLE
App under manteinance

### ISSUE THREAD

**Issue by albertodeago** [IliasHad/habitscript_vscode#4]
Hi, I wanted to try out this but it's a couple of days that I'm getting "Offline for maintenance" when I try to get to "https://habit-script.herokuapp.com/signup".

**Comment by IliasHad** [comment]
Hey Alberto,

Yes, the app is under maintenance because I have some functionality issues need to be fixed in the app to work correctly

Thanks,
Ilias

**Comment by albertodeago** [comment]
Oh okey, I'll wait for the app to be up and running again, then I'll try it out!

Thanks

**Comment by IliasHad** [comment]
Thank you so much :)

**Comment by ladaposamuel** [comment]
I'm also waiting for this, thanks

**Comment by josephbydeign** [comment]
looking forward to this being resolved.

**Comment by IliasHad** [comment]
Thank you so much for your support. HabitScript web app (Beta Version) is now available and I'm looking forward to hearing your feedback about it 

https://habit-script.herokuapp.com
